### ISSUE TITLE
New Skill: Discord Bot

### ISSUE THREAD

**Issue by philipp2310** [project-alice-powered-by-snips/ProjectAliceModules#101]
Let YOUR Alice join a specific discord channel.
Talk to her like it would be a room in your house

Usage:
- send commands from anywhere
- get notifications while not at home
- test new skills without really talking and don't annoy the rest of the room ;)

Risk:
- Security? Better user telegram/mail/whatever?

**Comment by maxbachmann** [comment]
voice over mail xD

**Comment by philipp2310** [comment]
While joining a Discord voice channel would be possible as well, I would go for the text only variant for now xD

**Comment by maxbachmann** [comment]
ah you mean text based :)
Yes I agree that this would be useful

**Comment by Psychokiller1888** [comment]
Problem is a bot is server wide, I'm not sure how it would target specific users

**Comment by maxbachmann** [comment]
not really doing much with discord, so I do not know whether it is possible to have a discord bot that is only chatting with one person. At least in telegram this should be possible

**Comment by philipp2310** [comment]
So it basically would be a serverwide bot user that could reply to anybody and read everything posted to any channel it is on.

How did I solve it previously? I have an own Server only for my house members and the bot.
Of course with the right skill set (or user permission setup) it could be a public bot as well, that can serve as some kind of "auto mod". But for me: I don't want anybody else to switch off my light over discord xD

As I don't use telegram, discord would be my go to service for now ^^

**Comment by maxbachmann** [comment]
I guess it might be a fun addition to have a alice installation for our discord server that can do some basic things like the calculator skill aswell

**Comment by philipp2310** [comment]
Routing all spoken text to a channel with the same name is done.
Next stop: Take the user written text(done) and start a new session with that as input.

Future:
enable text only (no real voice output by Alice) -> requires emulation of a few more Mqtt topics (sayFinished etc.)

**Comment by philipp2310** [comment]
Update:
Written messages are treated as input for Alice, she responds in the same discord channel. When there is a siteID with the same name as the channel, she will answer by voice as well.

Next stop:
refactoring!

**Comment by philipp2310** [comment]
https://github.com/philipp2310/skill_DiscordHook

working copy.
Next stop:
Add config for bot Token
Check for a discord.py version that works out of the box (currently keyboard interrupt events in the asyncio loop must be commented out manually - only in main thread)

**Comment by Psychokiller1888** [comment]
Very cool, good job! Will publish as soon as the new structure is live

**Comment by philipp2310** [comment]
Finally the Threads seem to be working in all cases and the pypi discord.py is working out of the box.
Config contains: Token, allowed Channels

Don't know any missing stuff for now - feel free to comment or just fork it in Project Alice!
https://github.com/philipp2310/skill_DiscordHook

And because I don't want to create an extra Issue for that: I created a tiny widget that allows to emulate Text input for Alice. Here I'm missing some error checks, but for DEVs (what it is ment for) it can be used!
https://github.com/philipp2310/skill_TextInputWidget
