### ISSUE TITLE
[BUG] RandomUselessFacts no longer works. Source site changed

### ISSUE THREAD

**Issue by hipitihop** [project-alice-powered-by-snips/ProjectAliceModules#112]
**Random Useless Facts no longer works**
The original site has changed so scraping does not work.

Reported by @mjlill on Discord #general 
>Sad news, appears  that https://uselessfacts.jsph.pl/ has changed the site so the skill uselessfacts doesn't work.  Anyone know how to scrape the page as they post some there now?  https://www.uselessfacts.net/c/Interesting

Rather then scraping their HTML, perhaps we should ask them if they have an API that open source projects like Alice can use ? ideally they should provide a JSON response format option.

**To Reproduce**

**Expected behavior**

**Logs**

```
Paste your logs here
```

**Alice version**
`1.0.0-a6`

**Additional context**

**Comment by Psychokiller1888** [comment]
Looks like there's no api anymore... We'll see, maybe they are rebuilding the site

**Comment by philipp2310** [comment]
api seems to be up again, will check

**Comment by philipp2310** [comment]
working for me without problems - please confirm for english and close

**Comment by philipp2310** [comment]
retest by mpbs
