### ISSUE TITLE
[New skill] OvenTemperatureConversion

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#113]
*Going through the correct skill submit process so i can test and see whats involved and advise if it needs tweaked :) *

- My skill name: OvenTemperatureConversion

- What does my skill do: 
Gives you the ability to ask Alice to convert temperatures between Celsius and Fahrenheit and visa versa. Also has a feature for those with gas ovens to ask Alice things like "what gas mark is 425 degrees Fahrenheit" or "Convert 170 C to gas mark"   she will reply with the correct gas mark for the oven

- The skill github repository url: https://github.com/LazzaAU/skill_OvenTemperatureConversion

- Did you check prior if there's already a skill existing that does the same?: **Yes**
 
  - If you answered yes:
    - Is there a skill already existing?: **No**
    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: **Yes**
  - If you answered yes: Perfect, thank you!
 
- Did you successfully run `projectalice-sk validate` on your skill? **Yes**
  - If you answered yes: Very well, you can continue!
 
- Do you believe in zombies? **Yes - there seems to be a new brain dead person on the news everyday :)**
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by Psychokiller1888** [comment]
Thank you!

Gitlab CI: https://gitlab.com/project-alice-assistant/skills/skill_OvenTemperatureConversion
Forked at: https://github.com/project-alice-assistant/skill_OvenTemperatureConversion

Your skill passed all tests and is now available in the store!

**Comment by Psychokiller1888** [comment]
Forget to mention: Please do subscribe to the fork, so you get alerted if anyone reports a bug
