### ISSUE TITLE
[Potential BUG ?] TextInputWidget skill

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#114]
**Describe the bug**
This may or may not be a expected outcome, but....
If using the TextInputWidget to trigger a responce from Alice that uses **self.continueDialog()**  Alice will run the code but NOT actually speak. Ask her the same thing via using your voice gives the expected outcome.

**To Reproduce**

1. i have the following code triggered from a intent. (my debug lines left in to show the code does get run fully... see log section below)
```
if` 'Number' not in session.slotsAsObjects:
			print("this is debug point number 1")
			print(session.sessionId),
			self.continueDialog(
				sessionId=session.sessionId,
				text=self.randomTalk('respondNoIdea'),
				currentDialogState=session.currentState
				)
 print("this is debug point number 2")
 print("Current dialog state is ")
 print(session.currentState)
```
That didnt format correctly when pasting but it works :) 

**Expected behavior**
Expected Alice to speak and then wait for a response. If using the TextInputWidget to trigger she runs the above code and outputs the below log but DOES NOT actually speak.

Repeat the process using your voice and Alice responds as expected. so this is just a text input related feature :)

**Logs**

```
[MqttManager]             Using probability threshold of 0.5
this is debug point number 1
9ee2e115-6e4d-4a28-bfa8-ac120f8dfd3a
this is debug point number 2
Current dialog state is 
OvenTemperatureConversion:default
[SkillManager]            The intent "convert2Celsius" was consumed by OvenTemperatureConversion

```

**Alice version**
B1

**Additional context**

**Comment by Psychokiller1888** [comment]
Unfortunately, as of now, the UI doesn't handle multi turn dialog through the text input widget.

**Comment by LazzaAU** [comment]
all right cool. good learning curve

**Comment by philipp2310** [comment]
recheck with new dialog manager, already possible?

**Comment by philipp2310** [comment]
implemented:
- new API /continue/ same as /process/ but requires a sessionId
- widget has a self filling/clearing sessionId field
