### ISSUE TITLE
Documentation duplicated text

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAliceModules#120]
**Describe the bug**
`https://docs.projectalice.io/skill-development/events.html#core-events`

**To Reproduce**
> def onCaptured(self, session)

Appears to be written twice

**Expected behavior**

**Logs**
Get your logs at ~/ProjectAlice/var/logs

```
Paste your logs here
```

**Alice version**
Master? Alpha, beta? What version?

**Additional context**

**Comment by Psychokiller1888** [comment]
thanks!
