### ISSUE TITLE
Admin button, utilities, reboot  does not work

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAliceModules#121]
**Describe the bug**
Title says it all, it also generates an error just before stopping

Error while shutting down manager unknownManager: 'MqttManager'

**To Reproduce**
1. Go to 'admin button'
2. Click on 'utilities'
3. Scroll down to 'reboot'
4. does not reboot

**Expected behavior**

**Logs**
Get your logs at ~/ProjectAlice/var/logs

```
Paste your logs here
```

**Alice version**
Master? Alpha, beta? What version?

**Additional context**

**Comment by Psychokiller1888** [comment]
This doesn't belong to the skills repo
