### ISSUE TITLE
Alice hangs if satellite doesn't respond

### ISSUE THREAD

**Issue by mjlill** [project-alice-powered-by-snips/ProjectAliceModules#122]
**Describe the bug**

> 2020-04-05 22:39:36,961 [Thread-1] - [INFO] - [AliceCore]               Device with uid 0822680e-f16d-4458-9e39-829ec274b952 of type AliceSatellite in room office connected
2020-04-05 22:39:48,813 [Thread-17] - [WARNING] - [DeviceManager]           Device with uid 0822680e-f16d-4458-9e39-829ec274b952 has not given a signal since 5 seconds or more

This randomly occurs after a restart

**To Reproduce**

**Expected behavior**

**Logs**
Get your logs at ~/ProjectAlice/var/logs

```
Paste your logs here
```

**Alice version**
Master? Alpha, beta? What version?

**Additional context**

**Comment by Psychokiller1888** [comment]
She doesn't hang, she marks the device as disconnected because it did not send heartbeats
