### ISSUE TITLE
[New skill] Reminder

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#123]
- My skill name: Reminder

- What does my skill do: 
It performs reminder tasks and Timer tasks and food timer tasks and Alarms

- The skill github repository url: 
https://github.com/LazzaAU/skill_Reminder

- Did you check prior if there's already a skill existing that does the same?: Yes

  - If you answered yes:
    - Is there a skill already existing?: No
   
    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: Yes to the best of my knowledge :)
  - If you answered yes: Perfect, thank you!
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? Yes
  - If you answered yes: Very well, you can continue!
  

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by Psychokiller1888** [comment]
So you don't believe in zombies?

**Comment by LazzaAU** [comment]
think i answered that in the last skill i submitted :)

**Comment by Psychokiller1888** [comment]
:)

Thanks for your skill! It's now published:

Sonarcloud: https://sonarcloud.io/dashboard?id=project-alice-assistant_skill_Reminder
Gitlab: https://gitlab.com/project-alice-assistant/skills/skill_Reminder

ProjectAlice clone: https://github.com/project-alice-assistant/skill_Reminder
