### ISSUE TITLE
[IDEA] Reminder make a simple timer

### ISSUE THREAD

**Issue by poulsp** [project-alice-powered-by-snips/ProjectAliceModules#124]
An opportunity to make a simple timer when I make tea in the morning, I want a timer of 3-5 minutes, but the tea is done before I can set up a timer with all the questions answers. :)

Maybe a slot with synonyms "simple"
suggestions
synonyms:
simple
plain
~~fuck off~~
~~shut up~~
no question

**Comment by LazzaAU** [comment]
Feature added 

- Alice can now set a "Timer" (only) without a message by saying things like
    * set a quick timer for 3 minutes
    * create a short timer for 2 minutes
    * keywords to trigger this are : "quick", "short" "breif", "simple", "lazy"
    and she will now set a timer event without the need for a topic
    
    NOTE: the limitation on this quick timer function are.
        * if you reboot you'll loose the timer 
        * you wont be able to stop the timer as it has no topic
        * you won't be able to ask how longs left on the timer as it has no topic
        * This only works for timer event, not reminder or alarm events
