### ISSUE TITLE
[IDEA] TextInputWidget skill settings

### ISSUE THREAD

**Issue by poulsp** [project-alice-powered-by-snips/ProjectAliceModules#125]
It would be nice with a skill settings/config so you can choose which Site Id you want as default.

**Comment by Psychokiller1888** [comment]
You mean so that it auto fills?

**Comment by philipp2310** [comment]
shouldn't do stuff without first having a look at the issue again - hope you didn't already start as well :/

https://github.com/project-alice-assistant/skill_TextInputWidget/compare/3466cc6fa1...37d3180772

**Comment by poulsp** [comment]
Yes I mean autofill.
Philipp, how do you set those options?

**Comment by philipp2310** [comment]
On the widget page, 
go into edit mode (pencil in the corner)
click on the cog for the settings
click on the cog of the widget you want to adjust
enter your values in the popup
- save and maybe reload!

**Comment by philipp2310** [comment]
just noticed there is an issue with small screens: the text for the two parameters might not be visible
first one is siteId
second one is username

will take care of that in a while

**Comment by poulsp** [comment]
Works as it should, apart from that it demand a big screen.
