### ISSUE TITLE
[New skill] - Broadcast

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#127]
- My skill name: Broadcast

- What does my skill do: Hopefully work :)... send broadcast messages to and from Alice and available satellites

- The skill github repository url: https://github.com/LazzaAU/skill_Broadcast

- Did you check prior if there's already a skill existing that does the same?: Yes
  
  - If you answered yes:
    - Is there a skill already existing?: No
   
    - If you answered no:
      - Great, let's continue!.... alright cool, lets do that *high five*

- Did you make sure your skill follows our code guidelines?: as per usual, yes to the best of my abilities :)
  - If you answered yes: Perfect, thank you!..... your welcome.... thanks SONAR :)
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? .....nope that's old school... i use sonar nowdays :) can i still continue boss ? 
  - If you answered yes: Very well, you can continue!
  - If you answered no: Really? [Publishing a skill](https://docs.projectalice.io/skill-development/publishing-to-skill-store)

- Do you believe in zombies? Yes, i'm almost certain i divorced one many years ago 
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by Psychokiller1888** [comment]
Great job, thank you!

The fork is here: https://github.com/project-alice-assistant/skill_Broadcast
