### ISSUE TITLE
[New skill] - HomeAssistant

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#130]
- My skill name: HomeAssistant

- What does my skill do: Connects Alice to Home Assistant (HA) via a RESTful API. It then allows Alice to 
1. Get a list of HA devices
2. Automagically write synonyms to dialogtemplate of known devices
3. Allows Alice to then turn on and off switches controlled by HA
4 and other features such as send certain sensor data to telemetry skill, report on dusk and dawn etc 

Basically gives existing HA users the abilty to make Alice do functional stuff with very little effort
When Alice does her own switching of devices i'm happy to make it so they don't clash also :)

- The skill github repository url: https://github.com/LazzaAU/skill_HomeAssistant

- Did you check prior if there's already a skill existing that does the same?: Yes
 
    - Is there a skill already existing?: No
    
    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: Yes
  - If you answered yes: Perfect, thank you!... your welcome :)
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? No - i got the green lights from SONAR
  - If you answered yes: Very well, you can continue!
  - If you answered no: Really? [Publishing a skill](https://docs.projectalice.io/skill-development/publishing-to-skill-store)

- Do you believe in zombies? hhmm deja Vue... sure :)
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by Psychokiller1888** [comment]
Thanks!

Btw, did you know that Sonar does check for code still, and projectalice-sk does check for errors in dialog templates, install templates and others?

Repo forked at: https://github.com/project-alice-assistant/skill_HomeAssistant

Please subscribe:
- https://gitlab.com/project-alice-assistant/skills/skill_HomeAssistant
- https://sonarcloud.io/dashboard?id=project-alice-assistant_skill_HomeAssistant
