### ISSUE TITLE
[New skill] BackUpAlice

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#131]
- My skill name: BackUpAlice

- What does my skill do: For forgetful people like me, it auto magically backs up the ProjectAlice folder to the home directory based on user configurable "days between backup". Handy utility for those of us living on the edge :-)

- The skill github repository url: https://github.com/LazzaAU/skill_BackUpAlice

- Did you check prior if there's already a skill existing that does the same?: Yes
  - If you answered no: **DO IT** and stop here. Return when you have checked
  - If you answered yes:
    - Is there a skill already existing?: No
    - If you answered yes:
      - Why, in your opinion, do you think we should publish yours?: 
    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: Yes
  - If you answered yes: Perfect, thank you!
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? Yes i did this time :)  
  - If you answered yes: Very well, you can continue!
  - If you answered no: Really? [Publishing a skill](https://docs.projectalice.io/skill-development/publishing-to-skill-store)

- Do you believe in zombies? Yes/No/Seriously?? yes
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by Psychokiller1888** [comment]
Thanks!

Your skill: https://github.com/project-alice-assistant/skill_BackUpAlice
Subscribe to:
- https://sonarcloud.io/dashboard?id=project-alice-assistant_skill_BackUpAlice
- https://gitlab.com/project-alice-assistant/skills/skill_BackUpAlice
