### ISSUE TITLE
[New skill] - Skill Translator

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#132]
*Dear Psycho,Good morning : ).*

- My skill name: skillTranslator

- What does my skill do: This skill will translate a skill to the supported 4 langaugaes. It's code flow is .....
- "hey alice" >> "translate my skill"
- Alice will then look in the skill settings to determine translation requirements ( skill name, skill's default language and a optional skill path)
- it will loop through all 3 non default languages and do the following:
- Translate the Talks file 
- then the dialog utterances
- then the dialog synonyms
- then update the install file

and that's it... *boom da bing da bang*... skill updated to all four supported languages and the Alice is now excited about her bilingual talents, however she still can't spell colour correctly : ) 

instructions explain a couple more options.also.

What this skill WONT do ( for now ).... 
- It wont translate markdown files. so instructions and readme arn't yet translated. 
- It won't make you breakfast 
- and it won't  allow you to do too many skills at once as google API will block your Ip and you'll have to wait .... and wait.... and wait.... and wait to use it again :-) (first hand experiance speaking)
- NO garuntee's its translated %100 accurately 

NOTE: The skill was tested and working perfectly other than a error when synonym[] was in the dialogTemplate file with no values. However i believe i fixed that but unable to test it since due to being blocked.

- The skill github repository url: https://github.com/LazzaAU/skill_SkillTranslator

- Did you check prior if there's already a skill existing that does the same?: Yes
  
  - If you answered yes:
    - Is there a skill already existing?: No

    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: yup
  - If you answered yes: Perfect, thank you! ..... your welcome 
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? Hell yes... and with every tool available to me  *grins*
  - If you answered yes: Very well, you can continue!.... Yayyyyy
  - If you answered no: Really? [Publishing a skill](https://docs.projectalice.io/skill-development/publishing-to-skill-store)

- Do you believe in zombies? Yes
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by LazzaAU** [comment]
I've made Enhancements to the Translator skill since original PR.

The skill now does the following

1. Translates talk files
2. Translates dialog files. It also removes the ```:=>keyValue}``` from the line to be translated, sends the line to google then puts that snippet back into the line so that it doesn't get translated and muck up the skills functionality.
3. Translates instructions providing they don't exceed googles quota values.
4. writes to install file to update language conditions   

Safe Guards
The skill has a "preCheck" mode which allows the user to do a dummy run on the skill without annoying google or writing to files. It then reports in syslog statistics or errors on the process for a informed user decision before translating

it also pauses the process if google quota's will be exceeded and then resumes when safe to do so. Helps reduce chances of having your IP blocked.

Tested successfully on three skills so far so fairly confident and therefore requesting a new review of the skill :)

**Comment by LazzaAU** [comment]
Also this morning just added option to translate only a selected folder if desired.. IE: just the dialog folder or Instructions or talks :)

**Comment by Psychokiller1888** [comment]
Thank you for your new skill! It was just added to our published skills:

Please subscribe to these:
- Get notified about new support tickets: https://github.com/project-alice-assistant/skill_SkillTranslator
- Get notified in case your new code quality is degrading: https://sonarcloud.io/dashboard?id=project-alice-assistant_skill_SkillTranslator
- Get notified if your new Pull Request failed building: https://gitlab.com/project-alice-assistant/skills/skill_SkillTranslator
