### ISSUE TITLE
[New skill] AliceVolume

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#135]
- My skill name: AliceVolume

- What does my skill do:

 Let's the user change the volume of Alice on the fly by saying things like , 
- set volume to %50, 
- raise volume by 10 percent 
etc etc 

- The skill github repository url : https://github.com/LazzaAU/skill_AliceVolume

- Did you check prior if there's already a skill existing that does the same?: Yes
  - If you answered no: **DO IT** and stop here. Return when you have checked
  - If you answered yes:
    - Is there a skill already existing?: No
    - If you answered yes:
      - Why, in your opinion, do you think we should publish yours?: 
    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: Yes
  - If you answered yes: Perfect, thank you!
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? Yes
  - If you answered yes: Very well, you can continue!
  - If you answered no: Really? [Publishing a skill](https://docs.projectalice.io/skill-development/publishing-to-skill-store)

- Do you believe in zombies? Yes/No/Seriously??
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by philipp2310** [comment]
Thank you for that skill :) was really waiting for something like that (baaad linux sound..^^)

This could be the perfect skill for "satellite skills", so skills that are installed and executed on the sat. as well. @Psychokiller1888 ;)

**Comment by Psychokiller1888** [comment]
Yes, I started implementing sat skills

**Comment by Psychokiller1888** [comment]
Thank you for your new skill! It was just added to our published skills:

Please subscribe to these:

Get notified about new support tickets: https://github.com/project-alice-assistant/skill_AliceVolume
Get notified in case your new code quality is degrading: https://sonarcloud.io/dashboard?id=project-alice-assistant_skill_AliceVolume
Get notified if your new Pull Request failed building: https://gitlab.com/project-alice-assistant/skills/skill_SkillAliceVolume
