### ISSUE TITLE
[New skill] HLCpattern

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-powered-by-snips/ProjectAliceModules#137]
- My skill name: HLC pattern

- What does my skill do: A simple skill to allow a user to change the pattern of their Alice LEDs as there is currently no easy way to do it once installed. The skill DOES use 3 sudo commands so please confirm if that's acceptable :)

- The skill github repository url: https://github.com/LazzaAU/skill_HLCpattern

- Did you check prior if there's already a skill existing that does the same?: Yes
  - If you answered no: **DO IT** and stop here. Return when you have checked
  - If you answered yes:
    - Is there a skill already existing?: No
    - If you answered yes:
      - Why, in your opinion, do you think we should publish yours?: 
    - If you answered no:
      - Great, let's continue!

- Did you make sure your skill follows our code guidelines?: Yes
  - If you answered yes: Perfect, thank you!
  - If you answered no: Well, no chance at publishing buddy.... [Code guidelines](https://docs.projectalice.io/contribute/code-guidelines)

- Did you successfully run `projectalice-sk validate` on your skill? Yes
  - If you answered yes: Very well, you can continue!
  - If you answered no: Really? [Publishing a skill](https://docs.projectalice.io/skill-development/publishing-to-skill-store)

- Do you believe in zombies? Yes
- If you answered seriously??:
  - **Do I look like I'm kidding?**

Ok, so you've gone through these steps, you can now submit your request. We'll fork your repository, make sure everything is in order and if yes we'll publish the skill. If anything is not ok, we'll get back in touch with you to get your skill published as soon as possible. Don't forget that once your skill is forked, you'll need to make Pull Requests to update your skill which will need the same approval.

**Comment by Psychokiller1888** [comment]
Thank you for this new skill!

It was just forked on https://github.com/project-alice-assistant/skill_HLCpattern and released!

Please subscribe to track your plugin's health:
https://github.com/project-alice-assistant/skill_HLCpattern
https://sonarcloud.io/project/configuration?id=project-alice-assistant_skill_HLCpattern
https://gitlab.com/project-alice-assistant/skills/skill_HLCpattern
