### ISSUE TITLE
endTalk parameters

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-powered-by-snips/ProjectAliceModules#14]
```python
managers.MqttServer.endTalk(
    sessionId=sessionId,
    text=managers.TalkManager.randomTalk('requireTasmotaModule'),
    client=siteId
)
```
in endTalk and similar functions theres always the parameter sessionId and client. Shouldn´t these parameters be known to the manager anyways?

in fact there are already a few calls to endTalk, where client is not added and even some where both are not added. Whats the reason they are added in the other places?

**Comment by Psychokiller1888** [comment]
client is of no use anymore, as the Snips session knows where to end a session. But sessionId is needed, to tell Snips which session you want to end :)

**Comment by maxbachmann** [comment]
thanks for the clarification
