### ISSUE TITLE
wrong sentences

### ISSUE THREAD

**Issue by maxbachmann** [project-alice-powered-by-snips/ProjectAliceModules#15]
https://github.com/project-alice-powered-by-snips/ProjectAliceModules/blob/master/PublishedModules/ProjectAlice/ContextSensitive/talks/fr.json
appears to have the wrong sentences when compared to https://github.com/project-alice-powered-by-snips/ProjectAliceModules/blob/master/PublishedModules/ProjectAlice/ContextSensitive/talks/en.json
(the .py uses the two sentences used by the english version)

**Comment by Psychokiller1888** [comment]
Correct, these are the currency converter strings, dunno why

**Comment by maxbachmann** [comment]
Also in https://github.com/project-alice-powered-by-snips/ProjectAliceModules/blob/master/PublishedModules/ProjectAlice/RedQueen/talks/fr.json the translations for onGoingBed are missing :)

**Comment by Psychokiller1888** [comment]
onGoingBed missing is normal, it's because I have in mind that alice creates a github issue when she's missing a translation
