### ISSUE TITLE
Utterances and being nice to Alice

### ISSUE THREAD

**Issue by glueckself** [project-alice-powered-by-snips/ProjectAliceModules#40]
Hi!

When writing utterances, do I have to write all of them with and without "please" (e.g. "Please play music", "play music", "Please turn on the music", "Turn on the music", ...) for the mood system to work or do I just write the simple version ("play music", "Turn on the music") and the NLU takes care of "please"? (or is the other way around - all utterances must contain "please"? or does it matter at all?)

I'm hope this is the right place to ask and that I didn't miss anything in the wiki.

Thanks!

**Comment by Psychokiller1888** [comment]
Nope, you don't need to append please to all your utterances, make some with and some without, it increases the match percentage.

**Comment by glueckself** [comment]
Ok, thanks.
Have I missed that in the wiki? If not, would you mind adding that? I guess other people might ask the same.

**Comment by maxbachmann** [comment]
I do not think so, but you write utterances here the same way you would for normal snips.

**Comment by Psychokiller1888** [comment]
Well, yeah, utterances are ways for your intent to be spoken by any random people. Some will ask nicely such as "Please play the next track", others would rather just use "next track". Utterances are comparators to the voice that's been captured. If I have an utterance that is "please play the next track", me saying "please play the next track" should be a 100% match, but me saying "play the next track" would be an 80% match, which is still enough for the intent to be triggered

**Comment by glueckself** [comment]
I see, thank you!
