### ISSUE TITLE
Conversion of snips skills

### ISSUE THREAD

**Issue by DanBmh** [project-alice-powered-by-snips/ProjectAliceModules#96]
Do you have or plan to write a script for automatic conversion from snips skill layout to your layout?

Im thinking about converting my snips skills to be usable with alice, but for now i only moved the exported data from snips console to my git repository (See for example: https://gitlab.com/DANBER/Snips-MusicMaster). 

As the conversion to your dialogTemplate form by hand would be very time consuming it would be very helpful if this could be done automatically.

**Comment by Psychokiller1888** [comment]
I could look if a parser would be imaginable yes

**Comment by maxbachmann** [comment]
the slots appear to have the same structure, so only the intents need the work.

**Comment by Psychokiller1888** [comment]
I used to love parsing. So I'll check what I can do
