### ISSUE TITLE
New Skill: Tasmota Temperature Logging

### ISSUE THREAD

**Issue by philipp2310** [project-alice-powered-by-snips/ProjectAliceModules#99]
Add MQTT messages from a tasmota device with temperature, humidity, atmospheric pressure to the telemetry database.

Supporting multiple rooms

Additional:
Make a widget(per room?) to display the current temperature

**Comment by Psychokiller1888** [comment]
That will be included for telemetry, but global device

**Comment by philipp2310** [comment]
temperature logging in telemetry has since been included for bme280, dht11 and dht22 into the tasmota skill.
Displaying in widget/myHome remains open

**Comment by philipp2310** [comment]
creating new issue with more fitting name for displaying the telemetry
